const express = require("express");
const bodyParser = require("body-parser");
const { sequelize } = require("./model");
const { getProfile } = require("./middleware/getProfile");
const { handleErrors } = require("./middleware/handleErrors");
const contractsRouter = require("./routers/contractsRouter");
const jobsRouter = require("./routers/jobsRouter");
const balancesRouter = require("./routers/balancesRouter");
const adminRouter = require("./routers/adminRouter");
const app = express();
app.use(bodyParser.json());
app.set("sequelize", sequelize);
app.set("models", sequelize.models);
app.use("/contracts", contractsRouter);
app.use("/jobs", jobsRouter);
app.use("/balances", balancesRouter);
app.use("/admin", adminRouter);
app.use(handleErrors);

module.exports = app;
